# routename:
#       path: ...
#       parameters:
#           name:
#               regexp:
#               default:
#           ...
#  ...

load:
    - App\Actions\Main

create-admin:
    path: "/framework/create/admin"
    method: POST
    action:
        class: App\Actions\Main
        method: createAdmin

generate-url:
    path: "/framework/generate-url"
    method: GET
    action:
        class: App\Actions\Main
        method: generateUrlResponse

# users routes
users:
    path: "/users"
    method: GET
    action:
        class: App\Actions\Users
        method: usersInterface

users-create-form:
    path: "/users/create/form"
    method: GET
    action:
        class: App\Actions\Users
        method: createForm

users-create-action:
    path: "/users/create/action"
    method: POST
    action:
        class: App\Actions\Users
        method: createAction

users-edit-form:
    path: "/users/$public_id/edit/form"
    method: GET
    parameters:
        public_id:
            regex: "[A-Za-z0-9-]+"
    action:
        class: App\Actions\Users
        method: editForm

users-edit-action:
    path: "/users/$public_id/edit/action"
    method: POST
    parameters:
        public_id:
            regex: "[A-Za-z0-9-]+"
    action:
        class: App\Actions\Users
        method: editAction

users-change-password-form:
    path: "/users/$public_id/change-password/form"
    method: GET
    parameters:
        public_id:
            regex: "[A-Za-z0-9-]+"
    action:
        class: App\Actions\Users
        method: passwordForm

users-change-password-action:
    path: "/users/$public_id/change-password/action"
    method: POST
    parameters:
        public_id:
            regex: "[A-Za-z0-9-]+"
    action:
        class: App\Actions\Users
        method: passwordAction

users-delete-action:
    path: "/users/$public_id/delete/action"
    method: POST
    parameters:
        public_id:
            regex: "[A-Za-z0-9-]+"
    action:
        class: App\Actions\Users
        method: deleteAction

login:
    path: "/login"
    method: GET
    action:
        class: App\Actions\Security
        method: login

check:
    path: "/security/login/action"
    method: POST
    action:
        class: App\Actions\Security
        method: check

logout:
    path: "/logout"
    method: GET
    action:
        class: App\Actions\Security
        method: logout