load:
    - Thor\Web\Assets\AssetController
    - Thor\Framework\Actions\Main
    - Thor\Framework\Actions\Configuration
    - Thor\Framework\Actions\Users
    - Thor\Framework\Actions\Permissions
    - Thor\Framework\Actions\Security
