- label: index
  icon: book
  route: index
- label: users
  icon: users
  route: users
  group:
    - icon: user-friends
      route: .
      label: users-groups
    - icon: user-check
      route: .
      label: users-roles
    - icon: badge-check
      route: .
      label: users-permissions
