# routename:
#       path: ...
#       parameters:
#           name:
#               regexp:
#               default:
#           ...
#  ...

index:
    path: "/"
    action:
        class: Thor\Controller\Main
        method: index

hello:
    path: "/hello/$name"
    parameters:
        name:
            regepx: "\\w+"
    action:
        class: Thor\Controller\Main
        method: hello

