# routename:
#       path: ...
#       parameters:
#           name:
#               regexp:
#               default:
#           ...
#  ...

# main routes
index:
    path: "/"
    method: GET
    action:
        class: Thor\Controller\Main
        method: index

changelog:
    path: "/changelog"
    method: GET
    action:
        class: Thor\Controller\Main
        method: changelog

create-admin:
    path: "/framework/create/admin"
    method: POST
    action:
        class: Thor\Controller\Main
        method: createAdmin

generate-url:
    path: "/framework/generate-url"
    method: GET
    action:
        class: Thor\Controller\Main
        method: generateUrlResponse

# users routes
users:
    path: "/users"
    method: GET
    action:
        class: Thor\Controller\Users
        method: usersInterface

users-create-form:
    path: "/users/create/form"
    method: GET
    action:
        class: Thor\Controller\Users
        method: createForm

users-create-action:
    path: "/users/create/action"
    method: POST
    action:
        class: Thor\Controller\Users
        method: createAction

users-edit-form:
    path: "/users/edit/$public_id"
    method: GET
    parameters:
        public_id:
            regex: "[A-Za-z0-9-]+"
    action:
        class: Thor\Controller\Users
        method: editForm
