userClass: Thor\App\Entities\User
usernameProperty: Username
passwordProperty: PwdHash

roles:
    dev:
        extends: admin
    admin:
        extends: user
    user: ~

configuration:
    base-role: user
    firewall-pattern: "^.*"
    login-url: "/login"
    logout-url: "/logout"
    check-url: "/check-login"
