security: true
pdo-handler: default
security-factory: 'Thor\Framework\Factories\SecurityFactory:produceSecurity'
user-class: 'Thor\Framework\Security\DbUser'
username-field: 'username'
firewalls:
    -
        pattern: /
        redirect: ~
        login-route: login
        logout-route: logout
        check-route: check
        exclude-route: ["load-asset"]
        exclude-path: []
