security: true

# option : firewall, protect routes
firewall:
    -   pattern: /
        redirect: ~ # public page to redirect if a status_forbidden is triggered, null -> login
        login-route: login
        logout-route: logout
        check-route: check
        exclude-path:
            - ''
            - ''
