userPdoRow:
    pdoRowClass: Thor\Api\Entities\User
    passwordCompareMethod: hasPwdHashFor
configuration:
    login-route: login
    logout-route: logout
    check-route: check
    session-key: token
    token-expire: 60
