source: 'git@github.com:/Trehinos/Thor.git'
composer-command: '~/composer.phar'
composer-options: '--ignore-platform-reqs'
migration-folder: migrations/
migration-index: 0
after-update: thor/after-update
